### ISSUE TITLE
Petabridge.Cmd raises NRE on connect 

### ISSUE THREAD

**Issue by vasily-kirichenko** [petabridge/petabridge.cmd-issues#23]
```
serializers {
  hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
}
serialization-bindings {
  "System.Object" = hyperion
}
```
```
$ pbm localhost:9110
 ____      _        _          _     _
|  _ \ ___| |_ __ _| |__  _ __(_) __| | __ _  ___
| |_) / _ | __/ _` | '_ \| '__| |/ _` |/ _` |/ _ \
|  __|  __| || (_| | |_) | |  | | (_| | (_| |  __/
|_|   \___|\__\__,_|_.__/|_|  |_|\__,_|\__, |\___|
                                       |___/

petabridge.cmd (0.2.2)
Copyright 2017 - 2017, Petabridge®.

serialization error: Object reference not set to an instance of an object.
```

**Comment by Aaronontheweb** [comment]
Hi @vasily-kirichenko 

I see you're using the v0.2.2 version of the client - which version of the host are you using? We moved from using Hyperion internally to Google Protobuf in v0.3.0 in order to ensure that the `pbm` client could be used cross-platform with .NET Core and .NET interchangeably. Users who are running ~0.3.* on the server and < 0.3.0 on the client have run into this NRE error upon connect before: https://github.com/petabridge/petabridge.cmd-issues/issues/11#issuecomment-329562188

Could you check the versions you're using of each?

**Comment by vasily-kirichenko** [comment]
0.2.2 is what choco installed. Should I install it in another way?

The host is of the latest version - 0.3.2.

**Comment by vasily-kirichenko** [comment]
Found the latest on https://cmd.petabridge.com/articles/install/downloads.html, let me try.

**Comment by vasily-kirichenko** [comment]
Works great, thanks you :)

**Comment by Aaronontheweb** [comment]
Glad we could help! v0.3.2 is up on Chocolatey: https://chocolatey.org/packages/petabridge-cmd

In the future you can run `choco update petabridge-cmd` whenever there's a new release and it'll pull down the latest.
