### ISSUE TITLE
dotnet tool install --global pbm fails on .NETCore 3.1

### ISSUE THREAD

**Issue by rlefever68** [petabridge/petabridge.cmd-issues#38]
## Description
Installation of Petabridge client using **dotnet tool install --global pbm*  fails on Ubuntu 18 with .NETCore 3.1
## What I get
![image](https://user-images.githubusercontent.com/3107063/97478144-d796e280-1950-11eb-9530-609829594834.png)
## What I expect
working petabridge client installed via dotnet tool install.

**Comment by IgorFedchenko** [comment]
Hello @rlefever68 

I tried to reproduce your issue on fresh Ubuntu 18.04 installation, but `pbm` was installed without errors.
What I did:

1. Run fresh ubuntu 18.04 image:
```docker run -it ubuntu:18.04```

2. Install .NET Core 3.1 (as described in the [MS docs](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#1804-)):
```
apt-get update
apt-get install -y wget
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
apt-get update; apt-get install -y apt-transport-https && apt-get update && apt-get install -y dotnet-sdk-3.1
```

3. Once installation process is finished, make sure dotnet is installed:
```
> dotnet --version
3.1.403
```

4. Try to install pbm:
```
> dotnet tool install --global pbm

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.403

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: pbm
Tool 'pbm' (version '0.8.0') was successfully installed.
```

It seems like there is some issue on your end. Make sure your internet connection is working and nuget feed is available (i.e. `wget https://api.nuget.org/v3/index.json` works). Finally, if nothing helps, try to reinstall/update your dotnet environment, since it is working on clean installation.
